# Generated by Django 5.1.7 on 2025-04-02 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collectionId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cName', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('initialPrice', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('quantitySold', models.IntegerField()),
                ('soldPrice', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('soldTo', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collectionId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='User.collection')),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('profileId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('profilePic', models.ImageField(upload_to='images/')),
                ('address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
