# Generated by Django 5.1.7 on 2025-04-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.IntegerField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permissionId', models.IntegerField(primary_key=True, serialize=False)),
                ('permissionName', models.CharField(max_length=100)),
                ('rolePermission', models.ManyToManyField(related_name='rolePermission', to='User.role')),
            ],
        ),
    ]
