# Generated by Django 5.1.7 on 2025-04-26 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('rId', models.AutoField(primary_key=True, serialize=False)),
                ('rName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='initialPrice',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='userId',
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('pId', models.AutoField(primary_key=True, serialize=False)),
                ('pName', models.CharField(max_length=100)),
                ('rolePermission', models.ManyToManyField(related_name='role_permission', to='User.role')),
            ],
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('ucId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('initialPrice', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.collection')),
                ('uId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('userRoleId', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role')},
            },
        ),
    ]
