# Generated by Django 5.1.7 on 2025-05-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_role_rename_cname_collection_collectionname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userName',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
