# Generated by Django 5.1.7 on 2025-05-03 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_role_rename_cname_collection_collectionname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='collectionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.collection'),
        ),
    ]
