# Generated by Django 5.1.7 on 2025-04-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_role_remove_collection_initialprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collectionId',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
