# Generated by Django 5.1.7 on 2025-04-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_role_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
