# Generated by Django 5.1.7 on 2025-04-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_delete_permission_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('rId', models.AutoField(primary_key=True, serialize=False)),
                ('rName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('pId', models.AutoField(primary_key=True, serialize=False)),
                ('pName', models.CharField(max_length=100)),
                ('rolePermission', models.ManyToManyField(related_name='role_permission', to='User.role')),
            ],
        ),
    ]
