# Generated by Django 5.1.7 on 2025-05-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_transaction_collectionid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='loss',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='profit',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='soldTo',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
