# Generated by Django 5.1.7 on 2025-05-04 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_transaction_loss_alter_transaction_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='User.usercollection'),
        ),
    ]
