# Generated by Django 5.1.7 on 2025-05-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_userprofile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(default='default.jpg', null=True, upload_to='ProfilePictures'),
        ),
    ]
