# Generated by Django 5.1.7 on 2025-05-04 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='cName',
            new_name='collectionName',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='initialPrice',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='collectionId',
        ),
        migrations.AddField(
            model_name='transaction',
            name='loss',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='userCollectionId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collectionId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='profit',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='soldTo',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userName',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permissionId', models.AutoField(primary_key=True, serialize=False)),
                ('permissionName', models.CharField(max_length=100)),
                ('rolePermission', models.ManyToManyField(related_name='role_permission', to='User.role')),
            ],
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('userCollectionId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('initialPrice', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.collection')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('userRoleId', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role')},
            },
        ),
    ]
