# Generated by Django 5.1.7 on 2025-05-04 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='userCollectionId',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.usercollection'),
        ),
    ]
