# Generated by Django 5.1.7 on 2025-05-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
    ]
