# Generated by Django 5.1.7 on 2025-05-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(default='/Default_pfp.jpg', null=True, upload_to='ProfilePictures/'),
        ),
    ]
